FROM icr.io/appcafe/websphere-traditional:9.0.5.14

# Add Type 4 JDBC driver (Db2)
COPY wlp/usr/shared/resources/Db2/db2jcc4.jar /opt/IBM/WebSphere/AppServer/universalDriver/lib/
USER root
RUN chown 1001:0 /opt/IBM/WebSphere/AppServer/universalDriver/lib/db2jcc4.jar
USER 1001

# Add Type 4 JDBC driver (MySQL) ... not available

ENV ENABLE_BASIC_LOGGING=true
RUN /work/configure.sh